### ISSUE TITLE
Country code param

### ISSUE THREAD

**Issue by vmtrue** [cianru/huawei-appgallery-publish-gradle-plugin#41]
Hello,

Is there any way to set up list of countries that my app would be available, or use countries from previous release?
Now when I publish the app by plugin I need to choose countries every time. When I publish the app manually I don't have to do such things, countries list got from previous release.

Thanks

**Comment by cosic** [comment]
@vmtrue Please try your changes on `1.3.5-SNAPSHOT` plugin version. Don't forget to add `maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }` repository.

**Comment by vmtrue** [comment]
@cosic Hi, I've checked publishing it works

**Comment by cosic** [comment]
I will add description how to fix issue for history.  

Just add `appBasicInfo` parametr into plugin extention

```
huaweiPublish {
    instances {
        release {
           ...
            appBasicInfo = "$projectDir/app-basic-info.json"
            ...
        }
    }
}
```

or use CLI param

```
./gradlew publishHuaweiAppGalleryRelease --appBasicInfo="./app/app-basic-info.json"
```

where `app-basic-info.json` contains json like this

```
{"publishCountry": "BY,MD,RU,AM,AZ,GE,KZ,KG,MN,TJ,TM,UZ"}
```
For more info and param options see API documentation https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-app-info-update-0000001111685198
