### ISSUE TITLE
Releases Notes object dint update New Features in App Information 

### ISSUE THREAD

**Issue by Maxwell6635** [cianru/huawei-appgallery-publish-gradle-plugin#44]
When we execute upload the build together releases notes object, but in store dint see the releases notes is updated in App Information

<img width="908" alt="Screenshot 2022-12-27 at 5 25 24 PM" src="https://user-images.githubusercontent.com/12591474/209644963-2940b78a-b8af-4106-881e-3731df2c7fea.png">

```
Setup : 
huaweiPublish {
    instances {
        stagingRelease {
            credentialsPath = "$rootDir/huawei-credentials.json"
            deployType = "publish"
            buildFormat = "apk"
            releaseTime = "2023-12-30T09:00:00+0800"
            releaseNotes = [
                    new ru.cian.huawei.publish.ReleaseNote(
                            "en-GB",
                            "$projectDir/release-notes-en.txt"
                    )
            ]
        }
}
```

Command : ./gradlew assembleStagingRelease publishHuaweiAppGalleryStagingRelease

**Comment by cosic** [comment]
@Maxwell6635 Hi. As a see there is inaccuracy in the specified data. You set "en-GB" in plugin settings but your screenshot shows "English (US) - default" description page. 

I guess you need to change or add a new one language 
```
huaweiPublish {
    instances {
        stagingRelease {
            credentialsPath = "$rootDir/huawei-credentials.json"
            deployType = "publish"
            buildFormat = "apk"
            releaseTime = "2023-12-30T09:00:00+0800"
            releaseNotes = [
                    new ru.cian.huawei.publish.ReleaseNote(
                            "en-US",
                            "$projectDir/release-notes-en.txt"
                    ),
                    new ru.cian.huawei.publish.ReleaseNote(
                            "en-GB",
                            "$projectDir/release-notes-en.txt"
                    )
            ]
        }
}
```

**Comment by Maxwell6635** [comment]
@cosic Ah I see thanks for helping again. :)

**Comment by cosic** [comment]
Hi, @rtsisyk 
>@cosic thanks for adding support for release-notes. It works like a charm.
>https://github.com/organicmaps/organicmaps/pull/4350#issuecomment-1407345589

Thanks. Glad to hear that.

>It would be better to support Triple-T structure, ...

I guess we've already discussed this issue with your collegue https://github.com/cianru/huawei-appgallery-publish-gradle-plugin/issues/37#issuecomment-1250874835. I still think that it's not a good idea to have a strong relations to other project. Instead I've created a flexible options of mine Release Notes decision to support any configuration. 

>...but I have solved this issue by this small Groovy snippet below:
>https://github.com/organicmaps/organicmaps/blob/93799b6977d761534c2e1bc043c15f9148aeebbb/android/build.gradle#L462-L480

Thanks a lot. I guess I will add your solution somewhere as example. 

>Do you have any plans to add support for appname, title, description?

Unfortunatеly [the Huawei Publishing API](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-app-info-update-0000001111685198) doen't have oportuneties to change `appname`, `title` and `description`. But if you would like to change Basic App Info you can. See `appBasicInfo` the Plugin parameter description.
