### ISSUE TITLE
Broken Task Configuration Avoidance

### ISSUE THREAD

**Issue by rmarma** [cianru/huawei-appgallery-publish-gradle-plugin#46]
### Problem
To establish a soft relationship between tasks, the plugin uses the [whenTaskAdded](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskCollection.html#whenTaskAdded-org.gradle.api.Action-) method. This breaks the [Task Configuration Avoidance](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html).
Scan for task `./gradlew :app:help`:
![plugin-task-configuration-avoidance-problem](https://user-images.githubusercontent.com/12980966/234941397-c4bf9421-e564-4dfe-905e-be8a68636f99.png)

### Quick fix
Replace `whenTaskAdded` with `configureEach`. But we are still losing "laziness" for the `publishHuaweiAppGallery` task in this line:
```kotlin
publishTask.get().mustRunAfter(this)
```
### Solution
We can be sure that the project contains `assemble` and `bundle` tasks, because the plugin is only used together with `com.android.application`:
```kotlin
project.plugins.withType<AppPlugin> {
    configureHuaweiPublish(project)
}
```

Therefore, we can establish the relationship between the tasks as follows:
```kotlin
project.tasks.register<HuaweiPublishTask>(publishTaskName, variant).configure {
    setMustRunAfter(
        setOf(
            project.tasks.named("assemble$variantName"),
            project.tasks.named("bundle$variantName"),
        )
    )
}
```

### Need testing!

**Comment by rmarma** [comment]
https://github.com/rmarma/huawei-appgallery-publish-gradle-plugin/pull/1

**Comment by cosic** [comment]
@rmarma Thank you for fix the configuration cache issue. Could you create Pull Request on `snapshot-1.3.6` branch on this repository?

**Comment by rmarma** [comment]
@cosic, done https://github.com/cianru/huawei-appgallery-publish-gradle-plugin/pull/47

**Comment by cosic** [comment]
@rmarma Thank you. I'm going to release it in a few days. You can try changes at 1.3.6-SNAPSHOT version now.

**Comment by rmarma** [comment]
@cosic, It works, but only on **JDK 18**:
![plugin-task-configuration-avoidance-result](https://user-images.githubusercontent.com/12980966/235353302-fc28e3d7-aca8-412b-b784-d47e8776912a.png)


On **JDK 17/11** get error:
```
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve ru.cian:huawei-publish-gradle-plugin:1.3.6-SNAPSHOT.
     Required by:
         project :
      > No matching variant of ru.cian:huawei-publish-gradle-plugin:1.3.6-SNAPSHOT:20230429.205109-1 was found. The consumer was configured to find a library for use during runtime, compatible with Java 17, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.1.1' but:
          - Variant 'apiElements' capability ru.cian:huawei-publish-gradle-plugin:1.3.6-SNAPSHOT declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 18 and the consumer needed a component for use during runtime, compatible with Java 17
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1.1')
          - Variant 'runtimeElements' capability ru.cian:huawei-publish-gradle-plugin:1.3.6-SNAPSHOT declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 18 and the consumer needed a component, compatible with Java 17
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1.1')
```

`1.3.6-SNAPSHOT:20230429.205109-1` compile with JDK 18?

**Comment by cosic** [comment]
> 1.3.6-SNAPSHOT:20230429.205109-1 compiled with JDK 18?

Yes, it compiled with JDK 18. I have been prepared new version for AGP 8+. But it seems a better way release configuration cache on JDK 11-17 and upto JDK 18 at next release.

**Comment by cosic** [comment]
So, I've published 2 versions: 
* `1.3.6-SNAPSHOT` – with fix configuration cache issue for JDK11-17
* `1.4.0-SNAPSHOT` – with fix configuration cache issue for JDK18+

**Comment by rmarma** [comment]
@cosic, thanks)

Why JDK 18? AFAIK, [AGP 8 requires JDK17](https://developer.android.com/build/releases/gradle-plugin#jdk-17-agp).

**Comment by cosic** [comment]
Actualy you are right. I shoult build it with JDK 17.

**Comment by rmarma** [comment]
@cosic, ok.

1.3.6 - JDK11+
1.4.0 - JDK17+

The problem is solved, we can close this issue.
