### ISSUE TITLE
client credentials  -  Can't get `accessToken`. Reason: 'Ret(code=203890688, msg=client id or secret error)'

### ISSUE THREAD

**Issue by tarikyurtlu** [cianru/huawei-appgallery-publish-gradle-plugin#57]
hi, I am trying to send apk to Huawei using the plugin you developed. However, I am getting the following error.

Can't get `accessToken`. Reason: 'Ret(code=203890688, msg=client id or secret error)'

Actually, when I checked, the client_id and client_secret values ​​are correct. I got them from oAuth via the API I created from Huawei Developer Console.

When I send a request to this endpoint with the same client_id and client_secret. I can get AccessToken.

https://oauth-login.cloud.huawei.com/oauth2/v3/token

When I send it to the endpoint you sent via postman, I get 502 ApsAuthBySecretReq.

Why am I getting this error?

<img width="981" alt="Screenshot 2024-09-14 at 10 30 25" src="https://github.com/user-attachments/assets/4b2f6ae8-15ed-4d44-be6b-4df01fe9928a">

<img width="703" alt="Screenshot 2024-09-14 at 11 05 43" src="https://github.com/user-attachments/assets/20679a98-eb90-46f6-8439-50197acbce97">

**Comment by cosic** [comment]
@tarikyurtlu Hi! As far as I saw by https://oauth-login.cloud.huawei.com/oauth2/v3/token you are using the token for [Huawei Kit Services](https://developer.huawei.com/consumer/en/doc/HMSCore-Guides/open-platform-oauth-0000001053629189). While the Plugin use [AppGallery Connect Services](https://developer.huawei.com/consumer/en/doc/AppGallery-connect-References/agcapi-obtain_token-0000001158365043) with request url 	
https://connect-api.cloud.huawei.com/api/oauth2/v1/token. I assume services are using different tokens.

**Comment by tarikyurtlu** [comment]
@cosic My aim was to check if the client_id and client_secret values ​​are correct. When an API goes with this information, the token is returned, while the API for AppGallery Connect Services says the client_id and client_secret values ​​are incorrect. Why does the same values ​​freeze with an error?

**Comment by tarikyurtlu** [comment]
Thanks I solved my problem. Credentials Type must be Admin of account type
